name: Build and Publish Docker image

on:
  push:
    branches: [ main ]
    tags: [ "v*" ]
  release:
    types: [ published ]
  workflow_dispatch:

env:
  IMAGE_NAME: vast-monitor

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute tags
        id: meta
        shell: bash
        run: |
          tags=(
            "ghcr.io/begna112/${IMAGE_NAME}:latest"
            "ghcr.io/begna112/${IMAGE_NAME}:${GITHUB_SHA}"
          )
          if [[ "${GITHUB_EVENT_NAME}" == "push" && "${GITHUB_REF}" == refs/tags/v* ]]; then
            version_tag=${GITHUB_REF#refs/tags/}
            tags+=("ghcr.io/begna112/${IMAGE_NAME}:${version_tag}")
          elif [[ "${GITHUB_EVENT_NAME}" == "release" ]]; then
            version_tag=${GITHUB_REF#refs/tags/}
            if [[ -z "${version_tag}" ]]; then
              version_tag="${{ github.event.release.tag_name }}"
            fi
            if [[ -n "${version_tag}" ]]; then
              tags+=("ghcr.io/begna112/${IMAGE_NAME}:${version_tag}")
            fi
          fi
          {
            printf 'tags<<EOF\n'
            printf '%s\n' "${tags[@]}"
            printf 'EOF\n'
          } >> "$GITHUB_OUTPUT"

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
